// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Crypto from "crypto";

function signData(data, privateKey) {
  return $$Crypto.sign("SHA256", data, {
              key: privateKey,
              dsaEncoding: "der"
            });
}

function verifySignature(data, signature, publicKey) {
  return $$Crypto.verify("SHA256", data, {
              key: publicKey,
              dsaEncoding: "der"
            }, signature);
}

export {
  signData ,
  verifySignature ,
}
/* crypto Not a pure module */
