// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as $$Crypto from "crypto";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function generateEcKeyPair() {
  try {
    var match = $$Crypto.generateKeyPairSync("ec", {
          namedCurve: "secp256k1"
        });
    return {
            TAG: "Ok",
            _0: [
              match.publicKey,
              match.privateKey
            ]
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      var msg = obj._1.message;
      if (msg !== undefined) {
        return {
                TAG: "Error",
                _0: {
                  TAG: "Error",
                  _0: msg
                }
              };
      } else {
        return {
                TAG: "Error",
                _0: {
                  TAG: "Error",
                  _0: "Unknown EC key pair generation error"
                }
              };
      }
    }
    throw obj;
  }
}

export {
  generateEcKeyPair ,
}
/* crypto Not a pure module */
