// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Crypto from "crypto";

function generate() {
  var match = $$Crypto.generateKeyPairSync("rsa", {
        modulusLength: 2048
      });
  return [
          match.publicKey,
          match.privateKey
        ];
}

export {
  generate ,
}
/* crypto Not a pure module */
