// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Crypto from "crypto";

function rsa() {
  var match = $$Crypto.generateKeyPairSync("rsa", {
        modulusLength: 2048
      });
  return [
          match.publicKey,
          match.privateKey
        ];
}

function ec() {
  var match = $$Crypto.generateKeyPairSync("ec", {
        namedCurve: "secp256k1"
      });
  return [
          match.publicKey,
          match.privateKey
        ];
}

export {
  rsa ,
  ec ,
}
/* crypto Not a pure module */
