// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Crypto from "crypto";

function sha256(data) {
  var hash = $$Crypto.createHash("sha256");
  return hash.update(data).digest("hex");
}

export {
  sha256 ,
}
/* crypto Not a pure module */
