// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as $$Crypto from "crypto";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function hashSha3(data) {
  try {
    var hash = $$Crypto.createHash("sha3-256");
    return {
            TAG: "Ok",
            _0: hash.update(data).digest("hex")
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      var msg = obj._1.message;
      if (msg !== undefined) {
        return {
                TAG: "Error",
                _0: {
                  TAG: "Error",
                  _0: msg
                }
              };
      } else {
        return {
                TAG: "Error",
                _0: {
                  TAG: "Error",
                  _0: "Unknown hashing error"
                }
              };
      }
    }
    throw obj;
  }
}

export {
  hashSha3 ,
}
/* crypto Not a pure module */
