// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sha256 from "./crypto/Hashing/Sha256.res.mjs";
import * as Generate from "./crypto/KeyPair/Generate.res.mjs";

var generateKeyPair = Generate.generate;

var hashSHA256 = Sha256.sha256;

export {
  generateKeyPair ,
  hashSHA256 ,
}
/* Sha256 Not a pure module */
