// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EC from "./crypto/KeyPair/EC.res.mjs";
import * as AES from "./crypto/Encryption/AES.res.mjs";
import * as RSA from "./crypto/KeyPair/RSA.res.mjs";
import * as SHA3 from "./crypto/Hashing/SHA3.res.mjs";
import * as ECDSA from "./crypto/Signature/ECDSA.res.mjs";
import * as Sha256 from "./crypto/Hashing/Sha256.res.mjs";

var generateRsaKeyPair = RSA.generateRsaKeyPair;

var generateEcKeyPair = EC.generateEcKeyPair;

var hashSHA256 = Sha256.hashSha256;

var hashSHA3 = SHA3.hashSha3;

var encryptAes = AES.encryptAes;

var decryptAes = AES.decryptAes;

var signData = ECDSA.signData;

var verifySignature = ECDSA.verifySignature;

export {
  generateRsaKeyPair ,
  generateEcKeyPair ,
  hashSHA256 ,
  hashSHA3 ,
  encryptAes ,
  decryptAes ,
  signData ,
  verifySignature ,
}
/* EC Not a pure module */
