// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Generate from "./crypto/KeyPair/Generate.res.mjs";

var generateKeyPair = Generate.generate;

export {
  generateKeyPair ,
}
/* Generate Not a pure module */
