// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Crypto from "./Crypto.res.mjs";

function add(a, b) {
  return a + b | 0;
}

console.log(3);

console.log($$Crypto.generateKeyPair());

export {
  add ,
}
/*  Not a pure module */
