// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Crypto from "./Crypto.res.mjs";

console.log($$Crypto.hashSHA256("Hello, World!"));

console.log($$Crypto.hashSHA3("Hello, World!"));

console.log($$Crypto.generateEcKeyPair());

var match = $$Crypto.generateEcKeyPair();

if (match.TAG === "Ok") {
  var match$1 = match._0;
  var signature = $$Crypto.signData("Hello, World!", match$1[1]);
  if (signature.TAG === "Ok") {
    var signature$1 = signature._0;
    console.log(signature$1);
    var isValid = $$Crypto.verifySignature("Hello, World!", signature$1, match$1[0]);
    console.log(isValid);
  } else {
    console.log("Error generating keys: " + signature._0._0);
  }
} else {
  console.log("Error generating keys: " + match._0._0);
}

var key = "12345678901234567890123456789012";

var iv = "1234567890123456";

var data = $$Crypto.encryptAes(key, iv, "Hello, ReScript!");

var encrypted;

encrypted = data.TAG === "Ok" ? data._0 : "Error during encryption";

console.log("Encrypted data: " + encrypted);

var decrypted = $$Crypto.decryptAes(key, iv, encrypted);

if (decrypted.TAG === "Ok") {
  console.log("Decrypted data: " + decrypted._0);
} else {
  console.log("Decryption error: " + decrypted._0._0);
}

export {
  key ,
  iv ,
  encrypted ,
}
/*  Not a pure module */
